# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sushma Ramanna
tagline:          'Developer & Web Artisan'
description:      'Developer & Web Artisan'
url:              http://www.sushmaramanna.com

author:
  name:           'Sushma Ramanna'
  url:            http://www.sushmaramanna.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/sushma-ramanna3/
