# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sushma Ramanna
tagline:          'Developer & Web Artisan'
description:      "I'm a Web Developer and Designer from Mandya, India. I enjoy taking complex problems. I also love the logic and structure of coding and always strive to write elegant and efficient code."
url:              http://www.sushmaramanna.com

author:
  name:           'Sushma Ramanna'
  url:            http://www.sushmaramanna.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/sushma-r/